data:
  dataset_name: "olistbr/brazilian-ecommerce"

paths:
  raw_data_dir: "data/raw/"
  processed_data_dir: "data/processed/"
  sql_dir: "src/etl/marts"

bigquery:
  project_id: "olist-data-warehouse-48014"
  datasets:
    raw: "olist_dw"
    core: "olist_core"
    analytics: "olist_analytics"
  sql_dir: "src/etl/marts/"
api:
  exchange_rate_url: "https://open.er-api.com/v6/latest/BRL"
